### ISSUE TITLE
is https://hub.docker.com/r/myon/fortivpn-socks5 trusted?

### ISSUE THREAD

**Issue by sijad** [Tosainu/docker-fortivpn-socks5#13]
would you please confirm that you're owner of https://hub.docker.com/r/myon/fortivpn-socks5 ?

**Comment by Tosainu** [comment]
Yes, `myon` is my account. However, I have migrated to use [ghcr.io/tosainu/fortivpn-socks5](https://github.com/tosainu/docker-fortivpn-socks5/pkgs/container/fortivpn-socks5) and that image is no longer updated.
